language: python
python:
  - "2.6"
  - "2.7"

cache: pip

# new travis infrastructure
sudo: false

git:
  depth: 1

env:
  global:
  matrix:
    - WITH_OPENTREP=0
    - WITH_OPENTREP=1

matrix:
  allow_failures:
    - python: "2.5"

notifications:
  email:
      - alexprengere@gmail.com

# install dependencies
install:
    - "pip install -U pip wheel"
    - "pip install ."

# run tests
script: "python test/test_GeoBases.py -vv"
